// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Pqm-O7WhI3wQMFZzOfYDSoTiBogKxoo',
    appId: '1:1003715697493:web:8bdbe95699315fb730addc',
    messagingSenderId: '1003715697493',
    projectId: 'simple-chat-3f6ab-477009',
    authDomain: 'simple-chat-3f6ab-477009.firebaseapp.com',
    databaseURL: 'https://simple-chat-3f6ab-477009-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'simple-chat-3f6ab-477009.firebasestorage.app',
    measurementId: 'G-NR43ZLEYXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowJkDdSa2U0Z6X84nH9RdclXpYeeA9K8',
    appId: '1:1003715697493:android:5c237d0cf60d565b30addc',
    messagingSenderId: '1003715697493',
    projectId: 'simple-chat-3f6ab-477009',
    databaseURL: 'https://simple-chat-3f6ab-477009-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'simple-chat-3f6ab-477009.firebasestorage.app',
  );

}